### ISSUE TITLE
Source Watch 报错；不支持较长的配置文件

### ISSUE THREAD

**Issue by ChaojuWang** [micro-in-cn/XConf#20]
1. 成功初始化配置源后，watch时报错
`2020-04-10 18:35:15  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://***/agent/api/v1/watch?appName=micro&clusterName=dev&namespaceName=jwt&updatedAt=": EOF]
`

2. 不支持拉取较长的配置文件（70行不到？）
curl 结果如下
`{"Error":"The entry size is larger than 1/1024 of cache size"}`
检查数据库，发现配置写进去了，agent拉取的时候出错？

**Comment by Allenxuxu** [comment]
https://github.com/micro-in-cn/XConf/blob/ee35d6160b858e7782c749d8b1cd241c5bcc14b7/agent-api/main.go#L22https://github.com/micro-in-cn/XConf/blob/ee35d6160b858e7782c749d8b1cd241c5bcc14b7/agent-api/main.go#L22

config.Init(client, 1024*1024)

尝试修改这里，扩大预分配内存，试试看。

**Comment by Allenxuxu** [comment]
https://github.com/micro-in-cn/XConf/commit/e3c5ba16eebd70d7ca8db5f03befa977ded4d471

这次 commit 支持自定义 cache 大小了

**Comment by ChaojuWang** [comment]
谢谢~
下班了==周一才有aws的access

**Comment by Allenxuxu** [comment]
> 谢谢~
> 下班了==周一才有aws的access

老哥试了吗，是不是这边设置缓存大小的问题

**Comment by ChaojuWang** [comment]
不好意思在忙其他的事情，测试了一下好像无效，测试文件大小大概0.8KB
k8s配置片段如下
`containers:
        - name: agent-api
          image: 'xuxu123/agent-api:latest'
          imagePullPolicy: Always
          env:
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8002
            - name: XCONF_CACHE_SIZE
              value: "1048576"`
endpoint返回值如下：
`{"Error":"The entry size is larger than 1/1024 of cache size"}`

agent-api -h里面好像没有关于cache size的说明，不知道是自动加还是需要手动写说明

**Comment by ChaojuWang** [comment]
Source Watch 报错的问题也还存在：
`2020-04-17 17:11:42  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://*/agent/api/v1/watch?appName=micro&clusterName=dev&namespaceName=db&updatedAt=": EOF]
`

**Comment by Allenxuxu** [comment]
@ChaojuWang cache size 的这个功能，我还没有 release 发布，所以最新的 docker 镜像里还没有这个功能。

**Comment by ChaojuWang** [comment]
Ok 那release后能在这里回复一下么~谢谢了

**Comment by Allenxuxu** [comment]
> Ok 那release后能在这里回复一下么~谢谢了

已经发布了 v0.1.3
docker 镜像建议指定版本

**Comment by ChaojuWang** [comment]
cache bug修复
改成指定版本了==谢谢
Source Watch的报错有头绪么~

**Comment by Allenxuxu** [comment]
> Source Watch 报错的问题也还存在：
> `2020-04-17 17:11:42 level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://*/agent/api/v1/watch?appName=micro&clusterName=dev&namespaceName=db&updatedAt=": EOF] `

"http://*/agent/api/v1/watch?

域名没传对吧

**Comment by ChaojuWang** [comment]
是的

**Comment by Allenxuxu** [comment]
老哥 k8s 部署成功了，可以 pr 个部署文档上来吗😄

**Comment by ChaojuWang** [comment]
ok没问题我写个部署文档

**Comment by Allenxuxu** [comment]
> ok没问题我写个部署文档

感谢🙏
放在 `XConf/deployments/` 这个目录

**Comment by ChaojuWang** [comment]
#22

**Comment by Allenxuxu** [comment]
好，感谢！
请问，这是准备上公司生产上用吗？

**Comment by ChaojuWang** [comment]
已经上开发环境了，稳定下来就上生产吧
