### ISSUE TITLE
npm run dev error!

### ISSUE THREAD

**Issue by cashwar3** [micro-in-cn/XConf#46]
npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
verbose stack Error: missing script: dev

进入package.json里面：
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "build:analyzer": "REACT_APP_NODE_ENV=analyzer react-app-rewired build",
    "test": "react-app-rewired test",
    "lint:fix": "eslint --fix --ext .js --ext .jsx --ext .ts --ext .tsx src",
    "generate": "bash ./generate.sh"
  },
没有dev选项

**Comment by Allenxuxu** [comment]
那就 npm run start 吧🐶

**Comment by cashwar3** [comment]
也会报错
