### ISSUE TITLE
source watch error: "...": EOF

### ISSUE THREAD

**Issue by ChaojuWang** [micro-in-cn/XConf#47]
还是以前的问题，始终没有解决
```
2020-06-29 11:33:13  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://***/agent/api/v1/watch?appName=micro&clusterName=dev&namespaceName=user_srv&updatedAt=": EOF]
```
source watcher报错

**Comment by Allenxuxu** [comment]
`http://***/agent/api/v1/watch`
域名没设置对吧

**Comment by ChaojuWang** [comment]
域名我打码了，配置能正常读取，但是读取之后就会频繁出现这个报错

**Comment by Allenxuxu** [comment]
贴下代码，我来试试。

**Comment by ChaojuWang** [comment]
```
import (
	"github.com/micro-in-cn/XConf/client/source"
)

...

func initCfg() {
	confsrc:=loadConfigSrc()
	basic.Init(confsrc...)

	err := config.C().App(appName, cfg)
	if err != nil {
		panic(err)
	}

	log.Logf("[initCfg] config，cfg：%v", cfg)

	return
}

func loadConfigSrc() (srcs []config.Option){
	var namespaces = []string{"***","***","***","***","***","***",appName}

	for _,n:=range namespaces{
		srcs=append(srcs,config.WithSource(source.NewSource("micro", "dev", n, source.WithURL("http://***/"))))
	}
	return
}

// part of code in basic.Init
{
...
c.conf, _ = config.NewConfig()
        // load config
	err = c.conf.Load(ops.Sources...)
	if err != nil {
		log.Fatal(err)
	}

	go func() {

		log.Logf("[init] watch config changes ...")
		watcher, err := c.conf.Watch()
		if err != nil {
			log.Fatal(err)
		}

		for {
			v, err := watcher.Next()
			if err != nil {
				log.Fatal(err)
			}

			log.Logf("[init] watch config changes: %v", string(v.Bytes()))
		}
	}()
...
}
```

**Comment by Allenxuxu** [comment]
"github.com/micro-in-cn/XConf/client/source"

先更新一下版本看看，这部分有过调整，现在的路径是这样 "github.com/micro-in-cn/XConf/pkg/client/source"

**Comment by Allenxuxu** [comment]
> ```
> import (
> 	"github.com/micro-in-cn/XConf/client/source"
> )
> 
> ...
> 
> func initCfg() {
> 	confsrc:=loadConfigSrc()
> 	basic.Init(confsrc...)
> 
> 	err := config.C().App(appName, cfg)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	log.Logf("[initCfg] config，cfg：%v", cfg)
> 
> 	return
> }
> 
> func loadConfigSrc() (srcs []config.Option){
> 	var namespaces = []string{"***","***","***","***","***","***",appName}
> 
> 	for _,n:=range namespaces{
> 		srcs=append(srcs,config.WithSource(source.NewSource("micro", "dev", n, source.WithURL("http://***/"))))
> 	}
> 	return
> }
> 
> // part of code in basic.Init
> {
> ...
> c.conf, _ = config.NewConfig()
>         // load config
> 	err = c.conf.Load(ops.Sources...)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	go func() {
> 
> 		log.Logf("[init] watch config changes ...")
> 		watcher, err := c.conf.Watch()
> 		if err != nil {
> 			log.Fatal(err)
> 		}
> 
> 		for {
> 			v, err := watcher.Next()
> 			if err != nil {
> 				log.Fatal(err)
> 			}
> 
> 			log.Logf("[init] watch config changes: %v", string(v.Bytes()))
> 		}
> 	}()
> ...
> }
> ```

你的这个用法也有问题，`err = c.conf.Load(ops.Sources...)` 并不是用来加载不同的配置的。

**Comment by ChaojuWang** [comment]
一个config只能有一个source对吧，最开始是因为config文件太长cache报错才分成好几个文件的
讲道理我们不需要watch。。所以下一步准备砍掉这一块23333
我明天试试吧

**Comment by Allenxuxu** [comment]
> 一个config只能有一个source对吧，最开始是因为config文件太长cache报错才分成好几个文件的
> 讲道理我们不需要watch。。所以下一步准备砍掉这一块23333
> 我明天试试吧

是的，一个config只能有一个source，不然Watch的时候也不知道 watch 哪一个 source 啊🐶。

cache 这个参数在启动agent 的时候可以设置。

现在go的客户端是适配的 go-micro 的config库，它的 Load 语意很迷，后续考虑单独做个 go 的client库。

**Comment by ChaojuWang** [comment]
make sense.
看样子我应该用一个warpper把多个配置文件封装起来

**Comment by Allenxuxu** [comment]
老哥，现在公司已经用上了吗？

**Comment by ChaojuWang** [comment]
开发环境已经用上了，等其他模块用gomicro重写后就准备上生产

**Comment by ChaojuWang** [comment]
话说感觉加一个配置聚合功能，把多个模块化的配置文件聚合成一个source的链接这个功能应该挺实用，毕竟微服务化之后很多像是etcd之类配置可能都是重复的

**Comment by Allenxuxu** [comment]
> 话说感觉加一个配置聚合功能，把多个模块化的配置文件聚合成一个source的链接这个功能应该挺实用，毕竟微服务化之后很多像是etcd之类配置可能都是重复的

嗯嗯，这个可以在 go client  sdk 里做，我记下来，后续安排上。

**Comment by Allenxuxu** [comment]
> 开发环境已经用上了，等其他模块用gomicro重写后就准备上生产

方便透露公司吗，我加到 README 里。

**Comment by ChaojuWang** [comment]
不好意思请问需要提供什么，我去问一下老板

**Comment by Allenxuxu** [comment]
> 不好意思请问需要提供什么，我去问一下老板

就是提供下公司名称，我放到说明里，说明哪些公司在使用本项目。

**Comment by ChaojuWang** [comment]
CHUR Networks

**Comment by Allenxuxu** [comment]
> CHUR Networks

感谢🙏，请问官网是这个吗 https://www.churnetworks.com/

**Comment by ChaojuWang** [comment]
是的没错

**Comment by Allenxuxu** [comment]
> 是的没错

👍好

**Comment by ChaojuWang** [comment]
现在一个source一个config，还是一样的错误，每个config都报这个错
最新的release里路径没有改变还是"github.com/micro-in-cn/XConf/client/source"
```2020-07-03 13:43:53  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://foo.bar:8080/agent/api/v1/watch?appName=foo&clusterName=foo&namespaceName=bar&updatedAt=": EOF]
```
updatedAt这个参数没有设置，手动访问这个url无任何返回

**Comment by Allenxuxu** [comment]
> 现在一个source一个config，还是一样的错误，每个config都报这个错
> 最新的release里路径没有改变还是"github.com/micro-in-cn/XConf/client/source"
> 
> ```
> 2020-07-03 13:43:53  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://foo.bar:8080/agent/api/v1/watch?appName=foo&clusterName=foo&namespaceName=bar&updatedAt=": EOF]
> ```
> 
> updatedAt这个参数没有设置，手动访问这个url无任何返回
> 感觉应该是agent里面的watch endpoint有bug

先排除下网络问题吧，是不是8080端口没开放，一般网络安全组会有这个配置。

上机器请求 http://127.0.0.1:8080 试试，如果这个也有问题，才说明 agent 有问题。

**Comment by ChaojuWang** [comment]
> > 现在一个source一个config，还是一样的错误，每个config都报这个错
> > 最新的release里路径没有改变还是"github.com/micro-in-cn/XConf/client/source"
> > ```
> > 2020-07-03 13:43:53  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://foo.bar:8080/agent/api/v1/watch?appName=foo&clusterName=foo&namespaceName=bar&updatedAt=": EOF]
> > ```
> > 
> > 
> > updatedAt这个参数没有设置，手动访问这个url无任何返回
> > 感觉应该是agent里面的watch endpoint有bug
> 
> 先排除下网络问题吧，是不是8080端口没开放，一般网络安全组会有这个配置。
> 
> 上机器请求 http://127.0.0.1:8080 试试，如果这个也有问题，才说明 agent 有问题。

部署在aws k8s上，配置能从8080正常读取，ui也能正常操作，就是不能watch

**Comment by Allenxuxu** [comment]
> > > 现在一个source一个config，还是一样的错误，每个config都报这个错
> > > 最新的release里路径没有改变还是"github.com/micro-in-cn/XConf/client/source"
> > > ```
> > > 2020-07-03 13:43:53  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://foo.bar:8080/agent/api/v1/watch?appName=foo&clusterName=foo&namespaceName=bar&updatedAt=": EOF]
> > > ```
> > > 
> > > 
> > > updatedAt这个参数没有设置，手动访问这个url无任何返回
> > > 感觉应该是agent里面的watch endpoint有bug
> > 
> > 
> > 先排除下网络问题吧，是不是8080端口没开放，一般网络安全组会有这个配置。
> > 上机器请求 http://127.0.0.1:8080 试试，如果这个也有问题，才说明 agent 有问题。
> 
> 部署在aws k8s上，配置能从8080正常读取，ui也能正常操作，就是不能watch

这个域名我能外网访问吗

**Comment by ChaojuWang** [comment]
> > > > 现在一个source一个config，还是一样的错误，每个config都报这个错
> > > > 最新的release里路径没有改变还是"github.com/micro-in-cn/XConf/client/source"
> > > > ```
> > > > 2020-07-03 13:43:53  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://foo.bar:8080/agent/api/v1/watch?appName=foo&clusterName=foo&namespaceName=bar&updatedAt=": EOF]
> > > > ```
> > > > 
> > > > 
> > > > updatedAt这个参数没有设置，手动访问这个url无任何返回
> > > > 感觉应该是agent里面的watch endpoint有bug
> > > 
> > > 
> > > 先排除下网络问题吧，是不是8080端口没开放，一般网络安全组会有这个配置。
> > > 上机器请求 http://127.0.0.1:8080 试试，如果这个也有问题，才说明 agent 有问题。
> > 
> > 
> > 部署在aws k8s上，配置能从8080正常读取，ui也能正常操作，就是不能watch
> 
> K8S 是不是会限制 HTTP 请求的时间，watch 的会挂起这次HTTP请求60s(HTTP LongPoll)

我正在查，应该不会

**Comment by ChaojuWang** [comment]
> > > > 现在一个source一个config，还是一样的错误，每个config都报这个错
> > > > 最新的release里路径没有改变还是"github.com/micro-in-cn/XConf/client/source"
> > > > ```
> > > > 2020-07-03 13:43:53  level=info [XConf] source watch error : %s (will sleep 1 second)[Get "http://foo.bar:8080/agent/api/v1/watch?appName=foo&clusterName=foo&namespaceName=bar&updatedAt=": EOF]
> > > > ```
> > > > 
> > > > 
> > > > updatedAt这个参数没有设置，手动访问这个url无任何返回
> > > > 感觉应该是agent里面的watch endpoint有bug
> > > 
> > > 
> > > 先排除下网络问题吧，是不是8080端口没开放，一般网络安全组会有这个配置。
> > > 上机器请求 http://127.0.0.1:8080 试试，如果这个也有问题，才说明 agent 有问题。
> > 
> > 
> > 部署在aws k8s上，配置能从8080正常读取，ui也能正常操作，就是不能watch
> 
> K8S 是不是会限制 HTTP 请求的时间，watch 的会挂起这次HTTP请求60s(HTTP LongPoll)

刚刚用postman测试了一遍，read接口正常返回200 和对应配置文件，watch接口1分钟后超时且并没有任何状态码返回
![image](https://user-images.githubusercontent.com/14054604/86449272-4aa19b00-bd5b-11ea-815e-09e4ff99a8fc.png)
![image](https://user-images.githubusercontent.com/14054604/86449392-791f7600-bd5b-11ea-9d91-ea6727fda99e.png)

**Comment by Allenxuxu** [comment]
你将你客户端的域名设成我这个看看能不能watch： xconf.mogutou.xyz

**Comment by ChaojuWang** [comment]
1m0.9s后返回304， 那应该是aws k8s的问题了。。我再去查一下reference

**Comment by ChaojuWang** [comment]
in the config of aws eks loadbalacer service:
```
metadata:
...
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "90"
...
```
issue solved.
