### ISSUE TITLE
建议添加多语种文本支持

### ISSUE THREAD

**Issue by ChaojuWang** [micro-in-cn/XConf#50]
请问有多语种文本切换的计划么
搭好了架子我可以提供英文本地化:)

**Comment by Allenxuxu** [comment]
> 请问有多语种文本切换的计划么
> 搭好了架子我可以提供英文本地化:)

是的，我们有这个计划 @SherryQueen

**Comment by Allenxuxu** [comment]
@ChaojuWang 英文支持已经加上，可以使用 v0.2.1。
线上demo 可以直接预览：http://xconf.mogutou.xyz/admin/ui/#/apps
