### ISSUE TITLE
前端有问题

### ISSUE THREAD

**Issue by zbhbz** [micro-in-cn/XConf#51]
搭好环境，前端自动跳到http://xconf.mogutou.xyz/admin/ui

**Comment by SherryQueen** [comment]
@zbhbz 能描述下大致的过程吗? 我这边复现一下, 查下原因.

**Comment by zbhbz** [comment]
第一，按照源码运行指南npm run dev，是指npm run start吗？
第二，运行npm run start后，在浏览器输入http://localhost:3000/admin/ui，自动跳转到http://xconf.mogutou.xyz/admin/ui。

**Comment by zbhbz** [comment]
已在issue回复 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;MySherry&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月15日(星期三) 晚上8:06
收件人:&nbsp;&quot;micro-in-cn/XConf&quot;<XConf@noreply.github.com&gt;;
抄送:&nbsp;&quot;zbH&quot;<191045643@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [micro-in-cn/XConf] 前端有问题 (#51)

**Comment by SherryQueen** [comment]
@zbhbz 先直接访问 localhost:3000 试试呢?
本地暂时是代理了线上的环境, 如果想再本地测试的话, 可以先修改这个代理链接
![image](https://user-images.githubusercontent.com/11926015/87544296-cb0bb880-c6d8-11ea-9223-6bb47d528630.png)

文档方面的话 我们到时候抽空改一下

**Comment by SherryQueen** [comment]
@zbhbz我这本地跑起来. 直接访问  http://localhost:3000/admin/ui 也是正常的额
![image](https://user-images.githubusercontent.com/11926015/87544600-5422ef80-c6d9-11ea-8de7-3c7af175f319.png)

**Comment by zbhbz** [comment]
<img width="1429" alt="图片" src="https://user-images.githubusercontent.com/13336469/87544830-a95f0100-c6d9-11ea-87b7-e4b1137be9db.png">

**Comment by SherryQueen** [comment]
@zbhbz  这看着应该是代理接口访问不对额.  你有调整过代码吗?

**Comment by zbhbz** [comment]
没有调过代码，就更改了刚刚你说的那个js，把地址改成localhost:3000

**Comment by SherryQueen** [comment]
@zbhbz 如果你本地起了服务的话. 那行代码改成

**Comment by SherryQueen** [comment]
如果你本地起了服务的话, 那段代码修改为如下 
```javascript
module.exports = function(app) {
  // http://127.0.0.1:8080 即本地服务的启动端口, 所有 /admin/api/v1 开头的请求会被转发到 http://127.0.0.1:8080 下
  app.use(createProxyMiddleware('/admin/api/v1', { target: 'http://127.0.0.1:8080', changeOrigin: true }));
};
```

如果是没有启动本地服务, 就不用修改代码 应该是能正常运行的

**Comment by zbhbz** [comment]
好了，谢谢

**Comment by SherryQueen** [comment]
@zbhbz 这个文档方面描述的不对, 代码更新了后文档没有及时同步, 带来不便 不好意思了. 我们到时候改一下
