### ISSUE TITLE
提几个问题

### ISSUE THREAD

**Issue by KaiwenWang** [micro-in-cn/XConf#7]
1. 分布式配置的引擎是什么？Eureca? Nacos? Zk?Etcd ? 如果是zk可以看看小米的shepher的架构。纯mysql可能要明确一下能力边界
2.阿波罗那套配置模型是否完全合理？
3.最好找个专业前端参与。可以参考小米shepher的配置编辑器实现
4.相比apollo 的优势在哪？golang项目部署更轻量级？apollo自身服务的发现等问题怎么解决？
5.找到种子用户，不然做着做着就没兴趣做下去了。哪怕强制在自己的公司推动使用也行

**Comment by Allenxuxu** [comment]
> 1. 分布式配置的引擎是什么？Eureca? Nacos? Zk?Etcd ? 如果是zk可以看看小米的shepher的架构。纯mysql可能要明确一下能力边界
>    2.阿波罗那套配置模型是否完全合理？
>    3.最好找个专业前端参与。可以参考小米shepher的配置编辑器实现
>    4.相比apollo 的优势在哪？golang项目部署更轻量级？apollo自身服务的发现等问题怎么解决？
>    5.找到种子用户，不然做着做着就没兴趣做下去了。哪怕强制在自己的公司推动使用也行

最近有点忙，很抱歉现在才回复啊😅
1. 确实是纯 mysql 的，主要是不想引入太多依赖，所有的配置信息都是存储在mysql中。
2. 阿波罗那套我觉得能满足绝大多数需求了。
3. 一直在找😭，没人
4. 使用的 go-micro ，比较灵活，服务发现使用 consul，etcd 等都可以，部署也更加方便。
5. 这个目前确实没有种子用户，不过会一直坚持的✊
