### ISSUE TITLE
希望能提供按原格式输出功能

### ISSUE THREAD

**Issue by dongdongvs6** [micro-in-cn/XConf#9]
假设在管理台发布了1个toml的配置文件。

希望客户端能支持获取该文件，并支持按toml格式输出到某个文件中。

**Comment by Allenxuxu** [comment]
最近有点忙，很抱歉现在才回复。
这是希望提供一个 agent 客户端吗，负责将服务器的配置同步到指定文件？

**Comment by Allenxuxu** [comment]
> 假设在管理台发布了1个toml的配置文件。
> 
> 希望客户端能支持获取该文件，并支持按toml格式输出到某个文件中。

目前已经在开发 agent 的进程了，可以实现单个配置文件实时更新到指定文件。

**Comment by dongdongvs6** [comment]
嗯，多谢，我会持续关注。
